# Site settings
title: Portafolio Juan Ceron
description: Portafolio Juan Ceron
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://williau

# User settings
username: Juan Ceron
user_description: Systems engineer with 3 years of experience, always focused on creating quality code. My specialty is Java, using Spring Framework, doing tests with Junit and managing code with Git. I have also worked with JavaScript, React and databases like MySQL and Firebase, along with other technologies.
user_title: Software Developer
email: juanceron256@gmail.com
github_username:  JuanCeron023


# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
